name: try-bug
base: core20
version: '0.1'
summary: demo
description: boilerplate 

grade: devel
confinement: strict

apps:
  d1:
    command: d1
    daemon: simple
  d2:
    command: d2
    daemon: simple

parts:
  launchers:
    plugin: dump
    source: launchers
